version: 0.2

phases:
  build:
    commands:
      - aws s3 cp s3://okky-config/settings.xml /root/.m2/settings.xml
      - mvn clean deploy -P prod

artifacts:
  files:
    - target/okky-share-event-1.0.0-SNAPSHOT.jar
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'